---
# tasks file for ansible-role-cloudforms-vmware-provision

- name: "Powering Off Virtual Machine"
  vmware_guest:
    hostname: vcenter-b900.rhpds.opentlc.com
    username: root
    password: "r3dh4t1!"
    datacenter: "{{ datacenter }}"
    validate_certs: no
    name: "{{ item.name }}"
    state: poweredoff
  register: vm_power_state
  with_items: "{{ service_vms }}"

- name: "Task Result: Powering Off Virtual Machine"
  debug: var=vm_power_state

- name: "Deleting Virtual Machine"
  vmware_guest:
    hostname: vcenter-b900.rhpds.opentlc.com
    username: root
    password: "r3dh4t1!"
    datacenter: "{{ datacenter }}"
    name: "{{ item.name }}"
    validate_certs: no
    state: absent
  register: vm_delete
  with_items: "{{ service_vms }}"

- name: "Task Result: Delete Virtual Machine"
  debug: var=vm_delete
